CREATE TABLE CLIENTDB 
(
  CNUM NUMBER(38, 0) NOT NULL 
, CID VARCHAR2(1000 BYTE) NOT NULL 
, CPW VARCHAR2(1000 BYTE) NOT NULL 
, CNAME VARCHAR2(1000 BYTE) NOT NULL 
, CBLACK NUMBER(10, 0) NOT NULL 
, BC NUMBER(*, 0) 
, CONSTRAINT CLIENTDB_PK PRIMARY KEY 
  (
    CNUM 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENTDB_PK ON CLIENTDB (CNUM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE CLIENTDB
ADD CONSTRAINT CIDU UNIQUE 
(
  CID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX CIDU ON CLIENTDB (CID ASC) 
    LOGGING 
    TABLESPACE USERS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

COMMENT ON COLUMN CLIENTDB.CNUM IS '회원번호';

COMMENT ON COLUMN CLIENTDB.CID IS '회원아이디';

COMMENT ON COLUMN CLIENTDB.CPW IS '회원비밀번호';

COMMENT ON COLUMN CLIENTDB.CNAME IS '회원명';

COMMENT ON COLUMN CLIENTDB.CBLACK IS '체납일';

COMMENT ON COLUMN CLIENTDB.BC IS '빌린권수';
-------------------------------------------------------------------------------------------
CREATE TABLE JAVABOOK 
(
  BNUM NUMBER(38, 0) NOT NULL 
, BNAME VARCHAR2(1000 BYTE) NOT NULL 
, BCOUNT NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE JAVABOOK
ADD CONSTRAINT BNAMEU UNIQUE 
(
  BNAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX BNAMEU ON JAVABOOK (BNAME ASC) 
    LOGGING 
    TABLESPACE USERS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

ALTER TABLE JAVABOOK
ADD CONSTRAINT BNU UNIQUE 
(
  BNUM 
)
USING INDEX 
(
    CREATE UNIQUE INDEX BNU ON JAVABOOK (BNUM ASC) 
    LOGGING 
    TABLESPACE USERS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

COMMENT ON COLUMN JAVABOOK.BNUM IS '책 번호';

COMMENT ON COLUMN JAVABOOK.BNAME IS '책 제목';

COMMENT ON COLUMN JAVABOOK.BCOUNT IS '책 권수';
--------------------------------------------------------------------------------------------
CREATE TABLE RENTDB 
(
  RNUM NUMBER(38, 0) NOT NULL 
, R_CID VARCHAR2(100 BYTE) NOT NULL 
, R_CNAME VARCHAR2(100 BYTE) NOT NULL 
, R_BNUM NUMBER(38, 0) NOT NULL 
, R_BNAME VARCHAR2(100 BYTE) NOT NULL 
, RENTD DATE NOT NULL 
, TURND DATE NOT NULL 
, EXCOUNT NUMBER(38, 0) NOT NULL 
, CONSTRAINT RENTDB_PK PRIMARY KEY 
  (
    RNUM 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RENTDB_PK ON RENTDB (RNUM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE RENTDB
ADD CONSTRAINT ID_FK FOREIGN KEY
(
  R_CID 
)
REFERENCES CLIENTDB
(
  CID 
)
ENABLE;

ALTER TABLE RENTDB
ADD CONSTRAINT NUM_FK FOREIGN KEY
(
  R_BNUM 
)
REFERENCES JAVABOOK
(
  BNUM 
)
ENABLE;

COMMENT ON COLUMN RENTDB.RNUM IS '대여번호';

COMMENT ON COLUMN RENTDB.R_CID IS '회원아이디(FK)';

COMMENT ON COLUMN RENTDB.R_CNAME IS '회원성함';

COMMENT ON COLUMN RENTDB.R_BNUM IS '책번호(FK)';

COMMENT ON COLUMN RENTDB.R_BNAME IS '책 제목';

COMMENT ON COLUMN RENTDB.RENTD IS '대여일';

COMMENT ON COLUMN RENTDB.TURND IS '반납마감일';

COMMENT ON COLUMN RENTDB.EXCOUNT IS '연장횟수';
--------------------------------------------------------------------------------------------
CREATE TABLE TURNDB 
(
  TNUM NUMBER(38, 0) NOT NULL 
, T_CID VARCHAR2(1000 BYTE) NOT NULL 
, T_BNAME VARCHAR2(1000 BYTE) NOT NULL 
, BACKD DATE NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN TURNDB.TNUM IS '반납번호';

COMMENT ON COLUMN TURNDB.T_CID IS '반납 회원아이디';

COMMENT ON COLUMN TURNDB.T_BNAME IS '반납 도서명';

COMMENT ON COLUMN TURNDB.BACKD IS '반납일';
--------------------------------------------------------------------------------------------
create sequence scott.CNB
increment by 1
start with 1
minvalue 1
nocycle
nocache
noorder;

drop sequence CNB;

create sequence scott.CNC
increment by 1
start with 1
minvalue 1
nocycle
nocache
noorder;

drop sequence CNC;

create sequence scott.CNR
increment by 1
start with 1
minvalue 1
nocycle
nocache
noorder;

drop sequence CNR;

create sequence scott.CNT
increment by 1
start with 1
minvalue 1
nocycle
nocache
noorder;

drop sequence CNT;